FROM node:11.9
LABEL maintainer="maayoko@gmail.com"

USER root
RUN apt-get update && \
    mkdir /home/node/gateway
ADD . /home/node/gateway
RUN chown -R node: /home/node/gateway

USER node
WORKDIR /home/node/gateway
RUN yarn install && yarn build
EXPOSE 3000

CMD ["sh", "-c", "yarn start:prod"]